#
# Copyright © 2022 <a href="mailto:zhang.h.n@foxmail.com">Zhang.H.N</a>.
# Release under GPL License
#

logging:
    config: config/log4j2.xml
app:
  zjuClient:
    pubkeyUrl: https://zjuam.zju.edu.cn/cas/v2/getPubKey
    loginUrl: https://zjuam.zju.edu.cn/cas/login
    cookieCached: false
  autoCard:
    reportUrl: https://healthreport.zju.edu.cn/ncov/wap/default/index
    submitUrl: https://healthreport.zju.edu.cn/ncov/wap/default/save
    codeUrl: https://healthreport.zju.edu.cn/ncov/wap/default/code
    cronExpression: 0 0 9 * * ? *  ## 每天09:00:00触发
    immediate: false
    config: "file://config/application.json"
mail:
    transport:
        protocol: smtp
    store:
        protocol: imap
    smtp:
        class: com.sun.mail.smtp.SMTPSSLTransport
        host: smtp.zju.edu.cn
        port: 994
        starttls:
            enable: true
        ssl:
            enable: true
            protocols: TLSv1.2
        auth: true
    imap:
        class: com.sun.mail.imap.IMAPSSLStore
        port: 993
        host: imap.zju.edu.cn
    debug: false
